### PR TITLE
Feature: Custom S3 ACL Configuration

### PR DESCRIPTION
**Pull request by krak3n**
This PR adds a new `STORE_S3_ACL` configuration option allowing users to set a different `ACL` for their uploaded files.

See http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl for reference.

### CODE REVIEW

**Comment by krak3n** [comment]
@thisissoon/members please review :smile:

**Comment by radeklos** [comment]
:+1:

**Comment by peeklondon** [comment]
:+1:

**Pull request merged**
